version: "3"

services:
  web:
    image: "apache:php8.2"
    restart: 'always'
    depends_on:
      - mariadb
    ports:
      - '8080:80'
    links:
      - mariadb
  mariadb:
    image: "mariadb:10.6"
    volumes: 
      - "/var/lib/mysql/data:${MARIADB_DATA_DIR}"
      - "/var/lib/mysql/logs:${MARIADB_LOG_DIR}"
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: myuser
        MYSQL_PASSWORD: mypassword