version: "3"

services:
  web:
    image: "apache:php8"
    restart: 'always'
    depends_on:
      - mariadb
    ports:
      - '8080:80'
    links:
      - mariadb
  mariadb:
    image: "mariadb:10.6"
    volumes: 
        - ./dump/:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: myuser
        MYSQL_PASSWORD: mypassword